name: nothing
description: An interesting app made with Flutter.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons:
  flutter_spinkit:
  swipedetector:
  shake:
  fluttertoast:
  connectivity:
  youtube_player_flutter: 6.1.1
  animated_floatactionbuttons:
  gradient_text:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Caveat
      fonts:
        - asset: fonts/Caveat-Regular.ttf
